# Generated by Django 3.0.6 on 2020-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pages', models.IntegerField()),
                ('no_of_copies', models.IntegerField()),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'libapp_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booksissued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'libapp_booksissued',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'libapp_book_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicationhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ratings', models.IntegerField()),
            ],
            options={
                'db_table': 'libapp_publicationhouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'libapp_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('profilepicpath', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'libapp_student',
                'managed': False,
            },
        ),
    ]
