# Generated by Django 3.0.6 on 2020-05-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
