# Generated by Django 3.0.6 on 2020-05-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0002_auto_20200509_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='libapi.Publicationhouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
