# Generated by Django 3.0.6 on 2020-05-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0003_auto_20200509_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
    ]
